[build]
  base    = "/"
  publish = "public"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/service-worker.js"

  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"
